project:
  type: book
  output-dir: docs
book:
  title: Machine Learning and Deep Learning with R
  author:
    name: Maximilian Pichler and Florian Hartig
    url: https://www.uni-regensburg.de/biologie-vorklinische-medizin/theoretische-oekologie/mitarbeiter/maximilian-pichler/index.html
  date: Juni 2023
  site-url: https://TheoreticalEcology.github.io/machinelearning/
  repo-url: https://github.com/TheoreticalEcology/machinelearning
  repo-branch: master
  repo-actions: edit
  sharing:
  - twitter
  - facebook
  - linkedin
  chapters:
  - index.qmd
  - A1-GettingStarted.qmd
  - part: Machine Learning Workflow
    chapters:
    - A2-MachineLearningTasks.qmd
    - A3-BiasVarianceTradeOff.qmd
    - A4-MLpipeline.qmd
    - Exercises/Exercise_tasks.qmd
    - Exercises/Exercise_pipeline.qmd
  - part: Machine Learning Algorithms
    chapters:
    - B1-Trees.qmd
    - B2-Distance.qmd
    - B3-NeuralNetworks.qmd
  - part: Deep Learning
    chapters:
    - C1-TensorFlow.qmd
    - C2-DeepNeuralNetworks.qmd
    - C3-ConvolutionalNeuralNetworks.qmd
    - C4-RecurrentNeuralNetworks.qmd
    - C5-GNN.qmd
  - part: Interpretation and causality with ML
    chapters:
    - D1-causality.qmd
    - D2-explainableAI.qmd
  - part: Generative modelling with DL
    chapters:
    - E1-Autoencoder.qmd
    - E2-GAN.qmd
  appendices: 
  - Appendix-Datasets.qmd
engine: knitr
bibliography: references.bib
google-scholar: true
execute:
  freeze: auto
  cache: false
format:
  html:
    code-copy: hover
    theme:
      light: [flatly, questions.css]
      dark: [darkly, questions.css]
    css: include/webex.css
    include-after-body: include/webex.js
    grid:
      sidebar-width: 280px
      body-width: 800px
      margin-width: 220px
      gutter-width: 1.5em
editor: visual