project:
  type: book
  output-dir: docs
book:
  title: Machine Learning and Deep Learning with R
  author:
    name: Maximilian Pichler and Florian Hartig
    url: https://www.uni-regensburg.de/biologie-vorklinische-medizin/theoretische-oekologie/mitarbeiter/maximilian-pichler/index.html
  date: Juni 2024
  site-url: https://TheoreticalEcology.github.io/machinelearning/
  repo-url: https://github.com/TheoreticalEcology/machinelearning
  repo-branch: master
  repo-actions: edit
  sharing:
  - twitter
  - facebook
  - linkedin
  chapters:
  - index.qmd
  - A1-GettingStarted.qmd
  - part: Machine Learning Basics
    chapters:
    - A2-MachineLearningTasks.qmd
    - A3-BiasVarianceTradeOff.qmd
    - A4-MLpipeline.qmd
    # - A4-MLpipeline-mlr3.qmd
  - part: Understanding ML Algorithms
    chapters:
    - B1-Trees.qmd
    - B2-Distance.qmd
    - B3-NeuralNetworks.qmd
  - part: Explainable AI and causal ML
    chapters:
    - D2-explainableAI.qmd
    - D1-causality.qmd
  - part: Deep Learning
    chapters:
    - C2-DeepNeuralNetworks.qmd
    - C3-ConvolutionalNeuralNetworks.qmd
    - C4-RecurrentNeuralNetworks.qmd
    - C5-GNN.qmd
  # - part: Generative modelling with DL
  #   chapters:
  #   - E1-Autoencoder.qmd
  #   - E2-GAN.qmd
  appendices: 
  - Appendix-Datasets.qmd
  - C1-TensorFlow.qmd
  - A4-MLpipeline-mlr3.qmd
engine: knitr
bibliography: references.bib
google-scholar: true
execute:
  freeze: auto
  cache: false
format:
  html:
    code-copy: hover
    theme:
      light: [cosmo, questions.css]
      dark: [darkly, questions.css]
    css: include/webex.css
    include-after-body: include/webex.js
editor: visual