project:
  type: book
  output-dir: docs
book:
  title: Machine Learning and Deep Learning with R
  author:
    name: Maximilian Pichler and Florian Hartig
    url: https://www.uni-regensburg.de/biologie-vorklinische-medizin/theoretische-oekologie/mitarbeiter/maximilian-pichler/index.html
  date: Juni 2023
  site-url: https://TheoreticalEcology.github.io/MachineLearningAndDeepLearning/
  repo-url: https://github.com/TheoreticalEcology/MachineLearningAndDeepLearning
  repo-branch: master
  repo-actions: edit
  sharing:
  - twitter
  - facebook
  - linkedin
  chapters:
  - index.qmd
  - A1-GettingStarted.qmd
  - part: "Machine Learning Pipeline"
    chapters: 
    - A2-MachineLearningTasks.qmd
    - A3-BiasVarianceTradeOff.qmd
    - A4-MLpipeline.qmd
  appendices:
    - Appendix-Datasets.qmd
engine: knitr
bibliography: references.bib
google-scholar: true
execute:
  freeze: auto
  cache: false
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: include/webex.css
    include-after-body: include/webex.js
editor: visual

