\documentclass[a4paper,twoside]{tufte-book} %style file is in the same folder.

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
%\usepackage{german}

\usepackage{color}
\usepackage{xcolor}
\usepackage{framed}
\usepackage{listings}

\usepackage{graphicx}

\usepackage{multicol}              
\usepackage{multirow}
\usepackage{booktabs}
%\usepackage{natbib} 

\usepackage[innerrightmargin = 0.7cm, innerleftmargin = 0.3cm]{mdframed}
\usepackage{mdwlist}

\usepackage[]{hyperref}
\definecolor{darkblue}{rgb}{0,0,.5}
\hypersetup{colorlinks=true, breaklinks=true, linkcolor=darkblue, menucolor=darkblue, urlcolor=blue, citecolor=darkblue}

\usepackage[toc,page]{appendix}


\setcounter{secnumdepth}{1}
\setcounter{tocdepth}{1}

\lstset{ % settings for listings needs to be be changed to R sytanx 
language=R,
breaklines = true,
columns=fullflexible,
breakautoindent = false,
%basicstyle=\listingsfont, 
basicstyle=\ttfamily \scriptsize,
keywordstyle=\color{black},                          
identifierstyle=\color{black},
commentstyle=\color{gray},
xleftmargin=3.4pt,
xrightmargin=3.4pt,
numbers=none,
literate={*}{{\char42}}1
         {-}{{\char45}}1
         {\ }{{\copyablespace}}1
}
% http://www.monperrus.net/martin/copy-pastable-listings-in-pdf-from-latex
\usepackage[space=true]{accsupp}
% requires the latest version of package accsupp
\newcommand{\copyablespace}{
    \BeginAccSupp{method=hex,unicode,ActualText=00A0}
\ %
    \EndAccSupp{}
}



<<setup, cache=FALSE, include=FALSE>>=
library(knitr)
opts_knit$set(tidy = T, fig=TRUE, fig.height = 4, fig.width=4, fig.align='center')
render_listings()
@

<<echo=FALSE, cache=TRUE, results='hide', message=FALSE, warning=FALSE>>=
set.seed(123)
@



\title{Machine Learning}
\author{MP Florian Hartig}


\begin{document}
%\SweaveOpts{concordance=TRUE} % don't activate this for knitr

\let\cleardoublepage\clearpage % No empty pages between chapters
\maketitle


\thispagestyle{empty}
\null


\href{Prof. Dr. Florian Hartig}{http://www.uni-regensburg.de/biologie-vorklinische-medizin/theoretische-oekologie/mitarbeiter/hartig/index.html}\\
University of Regensburg\\
Germany\\[0.5cm]

\begin{fullwidth}
Vorlesungsunterlagen für Studierende der

\begin{itemize*}
  \item BSc Biostatistik
  \item MSc Einführung in die Statistik mit R
\end{itemize*}

\vspace{0.5cm}

Fehler oder Verbesserungsvorschläge bitte über den \href{https://github.com/TheoreticalEcology/machinelearning/issues}{issue tracker} melden. 

\end{fullwidth}


\vfill
\begin{fullwidth}
Grundlagen der Statistik Version 0.1.2, compiled \today. Translated into German 2017, based on lecture notes "Essential Statistics", created 2014-2016. This work is licensed under a \href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License}. 
\end{fullwidth}


\newpage
\tableofcontents

\chapter{Introduction} % Use chapters instead of sections

\section{Goals of statistical inference}


\section{Machine learning models}

\section{Introduction to Keras / Tensorflow}


\chapter{The data analysis workflow}


\section{Data prepartion}

\section{Model fitting}

\section{Model validation}

\section{Inference}


\chapter{Important ML models}

\section{BRTs and RF}

\section{SVMs}

\section{ANNs and DNNs}

\section{CNNs}

\chapter{Advanced topics}



 
\end{document}
