<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Machine learning pipeline – Machine Learning and Deep Learning with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./B1-Trees.html" rel="next">
<link href="./A3-BiasVarianceTradeOff.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-43df0d6f53b733b42d37fa7808e17715.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-83a8ad1aaea65c9a121a74ba6090cc4e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-4ea8b931ddde2b266e468ba8229b5370.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
<meta name="citation_title" content="[[4]{.chapter-number}&nbsp; [Machine learning pipeline]{.chapter-title}]{#workflow .quarto-section-identifier}">
<meta name="citation_fulltext_html_url" content="https://TheoreticalEcology.github.io/machinelearning/A4-MLpipeline.html">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Regularization and variable selection via the elastic net;,citation_author=Hui Zou;,citation_author=Trevor Hastie;,citation_publication_date=2005;,citation_cover_date=2005;,citation_year=2005;,citation_issue=2;,citation_volume=67;,citation_journal_title=Journal of the royal statistical society: series B (statistical methodology);,citation_publisher=Wiley Online Library;">
<meta name="citation_reference" content="citation_title=Model averaging in ecology: A review of bayesian, information-theoretic, and tactical approaches for predictive inference;,citation_author=Carsten F Dormann;,citation_author=Justin M Calabrese;,citation_author=Gurutzeta Guillera-Arroita;,citation_author=Eleni Matechou;,citation_author=Volker Bahn;,citation_author=Kamil Bartoń;,citation_author=Colin M Beale;,citation_author=Simone Ciuti;,citation_author=Jane Elith;,citation_author=Katharina Gerstner;,citation_author=others;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_issue=4;,citation_volume=88;,citation_journal_title=Ecological Monographs;,citation_publisher=Wiley Online Library;">
<meta name="citation_reference" content="citation_title=Dropout: A simple way to prevent neural networks from overfitting;,citation_author=Nitish Srivastava;,citation_author=Geoffrey Hinton;,citation_author=Alex Krizhevsky;,citation_author=Ilya Sutskever;,citation_author=Ruslan Salakhutdinov;,citation_publication_date=2014;,citation_cover_date=2014;,citation_year=2014;,citation_issue=1;,citation_volume=15;,citation_journal_title=The journal of machine learning research;,citation_publisher=JMLR. org;">
<meta name="citation_reference" content="citation_title=Machine learning and deep learning—a review for ecologists;,citation_author=Maximilian Pichler;,citation_author=Florian Hartig;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_issue=4;,citation_volume=14;,citation_journal_title=Methods in Ecology and Evolution;,citation_publisher=Wiley Online Library;">
<meta name="citation_reference" content="citation_title=Deep learning as a tool for ecology and evolution;,citation_author=Marek L Borowiec;,citation_author=Rebecca B Dikow;,citation_author=Paul B Frandsen;,citation_author=Alexander McKeeken;,citation_author=Gabriele Valentini;,citation_author=Alexander E White;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_issue=8;,citation_volume=13;,citation_journal_title=Methods in Ecology and Evolution;,citation_publisher=Wiley Online Library;">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./A2-MachineLearningTasks.html">Machine Learning Basics</a></li><li class="breadcrumb-item"><a href="./A4-MLpipeline.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Machine learning pipeline</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Machine Learning and Deep Learning with R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/TheoreticalEcology/machinelearning" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A1-GettingStarted.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Machine Learning Basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A2-MachineLearningTasks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Machine Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A3-BiasVarianceTradeOff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Managing algorithmic complexity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A4-MLpipeline.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Machine learning pipeline</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Understanding ML Algorithms</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./B1-Trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tree-based Algorithms</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./B2-Distance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Distance-based Algorithms</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./B3-NeuralNetworks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Artificial Neural Networks</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Explainable AI and causal ML</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./D2-explainableAI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Explainable AI</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./D1-causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Causal Inference and Machine Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix-Datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A4-MLpipeline-mlr3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Machine learning framework - mlr3</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link active" data-scroll-target="#data-preparation"><span class="header-section-number">4.1</span> Data preparation</a>
  <ul class="collapse">
  <li><a href="#imputation" id="toc-imputation" class="nav-link" data-scroll-target="#imputation"><span class="header-section-number">4.1.1</span> Imputation</a></li>
  <li><a href="#preprocessing-and-feature-selection" id="toc-preprocessing-and-feature-selection" class="nav-link" data-scroll-target="#preprocessing-and-feature-selection"><span class="header-section-number">4.1.2</span> Preprocessing and Feature Selection</a></li>
  </ul></li>
  <li><a href="#modelling" id="toc-modelling" class="nav-link" data-scroll-target="#modelling"><span class="header-section-number">4.2</span> Modelling</a>
  <ul class="collapse">
  <li><a href="#split-data-for-final-predictions" id="toc-split-data-for-final-predictions" class="nav-link" data-scroll-target="#split-data-for-final-predictions"><span class="header-section-number">4.2.1</span> Split data for final predictions</a></li>
  <li><a href="#hyperparameter-optimization" id="toc-hyperparameter-optimization" class="nav-link" data-scroll-target="#hyperparameter-optimization"><span class="header-section-number">4.2.2</span> Hyperparameter optimization</a></li>
  </ul></li>
  <li><a href="#predictions-and-submission" id="toc-predictions-and-submission" class="nav-link" data-scroll-target="#predictions-and-submission"><span class="header-section-number">4.3</span> Predictions and Submission</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">4.4</span> Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/TheoreticalEcology/machinelearning/edit/master/A4-MLpipeline.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./A2-MachineLearningTasks.html">Machine Learning Basics</a></li><li class="breadcrumb-item"><a href="./A4-MLpipeline.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Machine learning pipeline</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="workflow" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Machine learning pipeline</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The Standard Machine Learning Pipeline using the Titanic Data set</p>
<p>Before we specialize on any tuning, it is important to understand that machine learning always consists of a pipeline of actions.</p>
<p>The typical machine learning workflow consist of:</p>
<ul>
<li>Data cleaning and exploration (EDA = explorative data analysis) for example with tidyverse.</li>
<li>Preprocessing and feature selection.</li>
<li>Splitting data set into training and test set for evaluation.</li>
<li>Model fitting.</li>
<li>Model evaluation.</li>
<li>New predictions</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/pipeline.png" class="img-fluid figure-img"></p>
<figcaption>Machine Learning pipeline</figcaption>
</figure>
</div>
<!-- Here is an (optional) video that explains the entire pipeline from a slightly different perspective: -->
<!-- ```{r chunk_chapter4_39, eval=knitr::is_html_output(excludes = "epub"), results = 'asis', echo = F} -->
<!-- cat( -->
<!--   '<iframe width="560" height="315"  -->
<!--   src="https://www.youtube.com/embed/nKW8Ndu7Mjw" -->
<!--   frameborder="0" allow="accelerometer; autoplay; encrypted-media; -->
<!--   gyroscope; picture-in-picture" allowfullscreen> -->
<!--   </iframe>' -->
<!-- ) -->
<!-- ``` -->
<p>In the following example, we use tidyverse, a collection of R packages for data science / data manipulation mainly developed by Hadley Wickham.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
dplyr and tidyverse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>dplyr</code> package is part of a framework called tidyverse. Unique features of the tidyverse are the pipe <code>%&gt;%</code> operator and <code>tibble</code> objects.</p>
<ul>
<li><p>The <code>%&gt;%</code> operator:</p>
<p>Applying several functions in sequence on an object often results in uncountable/confusing number of round brackets:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">mean</span>(<span class="fu">range</span>(<span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>The pipe operator simplifies that by saying “apply the next function on the result of the current function”:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>) <span class="sc">%&gt;%</span> range <span class="sc">%&gt;%</span> mean <span class="sc">%&gt;%</span> max</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>Which is easier to write, read, and to understand!</p></li>
<li><p><code>tibble</code> objects are just an extension of data.frames. In the course we will use mostly data.frames, so it is better to transform the tibbles back to data.frames:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>air_grouped <span class="ot">=</span> airquality <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Month)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(air_grouped)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "grouped_df" "tbl_df"     "tbl"        "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>air_grouped <span class="ot">=</span> <span class="fu">as.data.frame</span>(air_grouped)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(air_grouped)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div></li>
</ul>
</div>
</div>
</div>
<!-- ```{r chunk_chapter4_40, eval=knitr::is_html_output(excludes = "epub"), results = 'asis', echo = F} -->
<!-- cat( -->
<!--   '<iframe width="560" height="315"  -->
<!--   src="https://www.youtube.com/embed/nRtp7wSEtJA" -->
<!--   frameborder="0" allow="accelerometer; autoplay; encrypted-media; -->
<!--   gyroscope; picture-in-picture" allowfullscreen> -->
<!--   </iframe>' -->
<!-- ) -->
<!-- ``` -->

<div class="no-row-height column-margin column-container"><div class="">
<p>Another good reference is “<strong>R for data science</strong>” by Hadley Wickham: <a href="https://r4ds.had.co.nz/" target="_blank" rel="noopener"></a>.</p>
</div></div><p>For this lecture you need the Titanic data set provided by us (via the <code>EcoData</code> package).</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>You can find it in GRIPS (datasets.RData in the data set and submission section) or at <a href="http://rhsbio7.uni-regensburg.de:8500" target="_blank" rel="noopener">http://rhsbio7.uni-regensburg.de:8500</a> (VPN for University of Regensburg is required!).</p>
</div></div><div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivation - We need a model that can predict the survival probability of new passengers.
</div>
</div>
<div class="callout-body-container callout-body">
<p>We have split the data set into training and an outer test/prediction data sets (the test/prediction split has one column less than the train split, as the response for the test/outer split is unknown).</p>
<p><strong>The goal is to build a predictive model that can accurately predict the chances of survival for Titanic passengers!</strong></p>
<p>The dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EcoData)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(titanic_ml)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> titanic_ml</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The response variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(data<span class="sc">$</span>survived)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1  0 NA</code></pre>
</div>
</div>
<p>0 = passenger died</p>
<p>1 = passenger survived</p>
<p>NA = we don’t have information about the passenger, at the end, we will make predictions for these passengers!</p>
<p><strong>Important</strong>: Preprocessing of the data must be done for the training and testing data together!!</p>
</div>
</div>
<section id="data-preparation" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="data-preparation"><span class="header-section-number">4.1</span> Data preparation</h2>
<p>Load necessary libraries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Load data set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EcoData)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(titanic_ml)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> titanic_ml</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Standard summaries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1309 obs. of  13 variables:
 $ pclass   : int  2 1 3 3 3 3 3 1 3 1 ...
 $ survived : int  1 1 0 0 0 0 0 1 0 1 ...
 $ name     : chr  "Sinkkonen, Miss. Anna" "Woolner, Mr. Hugh" "Sage, Mr. Douglas Bullen" "Palsson, Master. Paul Folke" ...
 $ sex      : Factor w/ 2 levels "female","male": 1 2 2 2 2 2 2 1 1 1 ...
 $ age      : num  30 NA NA 6 30.5 38.5 20 53 NA 42 ...
 $ sibsp    : int  0 0 8 3 0 0 0 0 0 0 ...
 $ parch    : int  0 0 2 1 0 0 0 0 0 0 ...
 $ ticket   : Factor w/ 929 levels "110152","110413",..: 221 123 779 542 589 873 472 823 588 834 ...
 $ fare     : num  13 35.5 69.55 21.07 8.05 ...
 $ cabin    : Factor w/ 187 levels "","A10","A11",..: 1 94 1 1 1 1 1 1 1 1 ...
 $ embarked : Factor w/ 4 levels "","C","Q","S": 4 4 4 4 4 4 4 2 4 2 ...
 $ body     : int  NA NA NA NA 50 32 NA NA NA NA ...
 $ home.dest: Factor w/ 370 levels "","?Havana, Cuba",..: 121 213 1 1 1 1 322 350 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     pclass         survived          name               sex     
 Min.   :1.000   Min.   :0.0000   Length:1309        female:466  
 1st Qu.:2.000   1st Qu.:0.0000   Class :character   male  :843  
 Median :3.000   Median :0.0000   Mode  :character               
 Mean   :2.295   Mean   :0.3853                                  
 3rd Qu.:3.000   3rd Qu.:1.0000                                  
 Max.   :3.000   Max.   :1.0000                                  
                 NA's   :655                                     
      age              sibsp            parch            ticket    
 Min.   : 0.1667   Min.   :0.0000   Min.   :0.000   CA. 2343:  11  
 1st Qu.:21.0000   1st Qu.:0.0000   1st Qu.:0.000   1601    :   8  
 Median :28.0000   Median :0.0000   Median :0.000   CA 2144 :   8  
 Mean   :29.8811   Mean   :0.4989   Mean   :0.385   3101295 :   7  
 3rd Qu.:39.0000   3rd Qu.:1.0000   3rd Qu.:0.000   347077  :   7  
 Max.   :80.0000   Max.   :8.0000   Max.   :9.000   347082  :   7  
 NA's   :263                                        (Other) :1261  
      fare                     cabin      embarked      body      
 Min.   :  0.000                  :1014    :  2    Min.   :  1.0  
 1st Qu.:  7.896   C23 C25 C27    :   6   C:270    1st Qu.: 72.0  
 Median : 14.454   B57 B59 B63 B66:   5   Q:123    Median :155.0  
 Mean   : 33.295   G6             :   5   S:914    Mean   :160.8  
 3rd Qu.: 31.275   B96 B98        :   4            3rd Qu.:256.0  
 Max.   :512.329   C22 C26        :   4            Max.   :328.0  
 NA's   :1         (Other)        : 271            NA's   :1188   
                home.dest  
                     :564  
 New York, NY        : 64  
 London              : 14  
 Montreal, PQ        : 10  
 Cornwall / Akron, OH:  9  
 Paris, France       :  9  
 (Other)             :639  </code></pre>
</div>
</div>
<p>The name variable consists of 1309 unique factors (there are 1309 observations…) and could be now transformed. If you are interested in how to do that, take a look at the following box.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Feature engineering of the name variable
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1307</code></pre>
</div>
</div>
<p>However, there is a title in each name. Let’s extract the titles:</p>
<ol type="1">
<li>We will extract all names and split each name after each comma “,”.</li>
<li>We will split the second split of the name after a point “.” and extract the titles.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>first_split <span class="ot">=</span> <span class="fu">sapply</span>(data<span class="sc">$</span>name,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                     <span class="cf">function</span>(x) stringr<span class="sc">::</span><span class="fu">str_split</span>(x, <span class="at">pattern =</span> <span class="st">","</span>)[[<span class="dv">1</span>]][<span class="dv">2</span>])</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>titles <span class="ot">=</span> <span class="fu">sapply</span>(first_split,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                <span class="cf">function</span>(x) <span class="fu">strsplit</span>(x, <span class="st">"."</span>,<span class="at">fixed =</span> <span class="cn">TRUE</span>)[[<span class="dv">1</span>]][<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We get 18 unique titles:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(titles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>titles
         Capt           Col           Don          Dona            Dr 
            1             4             1             1             8 
     Jonkheer          Lady         Major        Master          Miss 
            1             1             2            61           260 
         Mlle           Mme            Mr           Mrs            Ms 
            2             1           757           197             2 
          Rev           Sir  the Countess 
            8             1             1 </code></pre>
</div>
</div>
<p>A few titles have a very low occurrence rate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>titles <span class="ot">=</span> stringr<span class="sc">::</span><span class="fu">str_trim</span>((titles))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>titles <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">fct_count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 2
   f                n
   &lt;fct&gt;        &lt;int&gt;
 1 Capt             1
 2 Col              4
 3 Don              1
 4 Dona             1
 5 Dr               8
 6 Jonkheer         1
 7 Lady             1
 8 Major            2
 9 Master          61
10 Miss           260
11 Mlle             2
12 Mme              1
13 Mr             757
14 Mrs            197
15 Ms               2
16 Rev              8
17 Sir              1
18 the Countess     1</code></pre>
</div>
</div>
<p>We will combine titles with low occurrences into one title, which we can easily do with the <code>forcats</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>titles2 <span class="ot">=</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  forcats<span class="sc">::</span><span class="fu">fct_collapse</span>(titles,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">officer =</span> <span class="fu">c</span>(<span class="st">"Capt"</span>, <span class="st">"Col"</span>, <span class="st">"Major"</span>, <span class="st">"Dr"</span>, <span class="st">"Rev"</span>),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">royal =</span> <span class="fu">c</span>(<span class="st">"Jonkheer"</span>, <span class="st">"Don"</span>, <span class="st">"Sir"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"the Countess"</span>, <span class="st">"Dona"</span>, <span class="st">"Lady"</span>),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">miss =</span> <span class="fu">c</span>(<span class="st">"Miss"</span>, <span class="st">"Mlle"</span>),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">mrs =</span> <span class="fu">c</span>(<span class="st">"Mrs"</span>, <span class="st">"Mme"</span>, <span class="st">"Ms"</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                        )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can count titles again to see the new number of titles:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>titles2 <span class="sc">%&gt;%</span>  </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">fct_count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  f           n
  &lt;fct&gt;   &lt;int&gt;
1 officer    23
2 royal       6
3 Master     61
4 miss      262
5 mrs       200
6 Mr        757</code></pre>
</div>
</div>
<p>Add new title variable to data set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">title =</span> titles2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<section id="imputation" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="imputation"><span class="header-section-number">4.1.1</span> Imputation</h3>
<p>NAs are a common problem in ML and most ML algorithms cannot handle NAs. For example, the age variable has 20% NAs:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
 0.1667 21.0000 28.0000 29.8811 39.0000 80.0000     263 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data<span class="sc">$</span>age)) <span class="sc">/</span> <span class="fu">nrow</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2009167</code></pre>
</div>
</div>
<p>There are few options how to handle NAs:</p>
<ul>
<li><p>Drop observations with NAs, however, we may lose many observations (not what we want!)</p></li>
<li><p>Imputation, fill the missing values</p></li>
</ul>
<p>We impute (fill) the missing values, for example with the median age. However, age itself might depend on other variables such as sex, class and title. Thus, instead of filling the NAs with the overall median of the passengers, we want to fill the NAs with the median age of these groups so that the associations with the other groups are preserved (or in other words, that the new values are hopefully closer to the unknown true values).</p>
<p>In <code>tidyverse</code> we can “group” the data, i.e.&nbsp;we will nest the observations within categorical variables for which we assume that there may be an association with age (here: <code>group_by</code> after sex, pclass and title). After grouping, all operations (such as our <code>median(age....)</code>) will be done within the specified groups (to get better estimates of these missing NAs).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(survived, sex, age, fare, pclass) <span class="sc">%&gt;%</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(sex, pclass) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">age2 =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(age), <span class="fu">median</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), age)) <span class="sc">%&gt;%</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">fare2 =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(fare), <span class="fu">median</span>(fare, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), fare)) <span class="sc">%&gt;%</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preprocessing-and-feature-selection" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="preprocessing-and-feature-selection"><span class="header-section-number">4.1.2</span> Preprocessing and Feature Selection</h3>
<p>Later (tomorrow), we want to use Keras in our example, but it cannot handle factors and requires the data to be scaled.</p>
<p>Normally, one would do this for all predictors, but as we only show the pipeline here, we have sub-selected a bunch of predictors and do this only for them. We first scale the numeric predictors and change the factors with only two groups/levels into integers (this can be handled by Keras).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>data_sub <span class="ot">=</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(survived, sex, age2, fare2, pclass) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">age2 =</span> scales<span class="sc">::</span><span class="fu">rescale</span>(age2, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">fare2 =</span> scales<span class="sc">::</span><span class="fu">rescale</span>(fare2, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as.integer</span>(sex) <span class="sc">-</span> <span class="dv">1</span>L,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">pclass =</span> <span class="fu">as.integer</span>(pclass <span class="sc">-</span> <span class="dv">1</span>L))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Transforming factors with more than two levels
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Factors with more than two levels should be <strong>one hot encoded</strong> (Make columns for every different factor level and write 1 in the respective column for every taken feature value and 0 else. For example: <span class="math inline">\(\{red, green, green, blue, red\} \rightarrow \{(0,0,1), (0,1,0), (0,1,0), (1,0,0), (0,0,1)\}\)</span>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>one_title <span class="ot">=</span> <span class="fu">model.matrix</span>(<span class="sc">~</span><span class="dv">0</span><span class="sc">+</span><span class="fu">as.factor</span>(title), <span class="at">data =</span> data)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(one_title) <span class="ot">=</span> <span class="fu">levels</span>(data<span class="sc">$</span>title)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>one_sex <span class="ot">=</span> <span class="fu">model.matrix</span>(<span class="sc">~</span><span class="dv">0</span><span class="sc">+</span><span class="fu">as.factor</span>(sex), <span class="at">data =</span> data)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(one_sex) <span class="ot">=</span> <span class="fu">levels</span>(data<span class="sc">$</span>sex)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>one_pclass <span class="ot">=</span> <span class="fu">model.matrix</span>(<span class="sc">~</span><span class="dv">0</span><span class="sc">+</span><span class="fu">as.factor</span>(pclass), <span class="at">data =</span> data)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(one_pclass) <span class="ot">=</span> <span class="fu">paste0</span>(<span class="st">"pclass"</span>, <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>pclass)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And we have to add the dummy encoded variables to the data set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">data.frame</span>(<span class="at">survived=</span> data<span class="sc">$</span>survived),</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                 one_title, one_sex, <span class="at">age =</span> data<span class="sc">$</span>age2,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fare =</span> data<span class="sc">$</span>fare2, one_pclass)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="modelling" class="level2 page-columns page-full" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="modelling"><span class="header-section-number">4.2</span> Modelling</h2>
<section id="split-data-for-final-predictions" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="split-data-for-final-predictions"><span class="header-section-number">4.2.1</span> Split data for final predictions</h3>
<p>To tune our hyperparameters and evaluate our models, we split the data into the training and testing data. The testing data are the observations where the response is NA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_sub<span class="sc">$</span>survived)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
 0.0000  0.0000  0.0000  0.3853  1.0000  1.0000     655 </code></pre>
</div>
</div>
<p>655 observations have NAs in our response variable, these are the observations for which we want to make predictions at the end of our pipeline.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>data_new <span class="ot">=</span> data_sub[<span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),]</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>data_obs <span class="ot">=</span> data_sub[<span class="sc">!</span><span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="hyperparameter-optimization" class="level3 page-columns page-full" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="hyperparameter-optimization"><span class="header-section-number">4.2.2</span> Hyperparameter optimization</h3>
<p>We want to tune our hyperparameters (<span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\alpha\)</span>). Normally, we should do a nested CV on our training data (data_obs), however, we assume that the test data on the submission server is our outer split, so we can tune our hyperparameters using a n-fold Cross-Validation which serves as our inner CV.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Again, why is it important to tune hyperparameters? Hyperparameters (configuration parameters of our ML algorithms that (mostly) control their complexity) are usually tuned (optimized) in an automatic / systematic way. A common procedure, called random search, is to sample random configuration combinations from the set of hyperparameters and test for each combination the prediction error.</p>
</div></div><p>We implement manually a CV to tune the learning rate. We start with a 3xCV and 10x different learning rates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cito)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">dnn</span>(survived<span class="sc">~</span>.,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> data_obs, </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">loss =</span> <span class="st">"binomial"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">lr =</span> <span class="fu">tune</span>(<span class="fl">0.001</span>, <span class="fl">0.1</span>),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">tuning =</span> <span class="fu">config_tuning</span>(<span class="at">CV =</span> <span class="dv">3</span>, <span class="at">steps =</span> <span class="dv">10</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 methods overwritten by 'reformulas':
  method       from
  head.call    cito
  head.formula cito
  head.name    cito</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Starting hyperparameter tuning...
Fitting final model...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model<span class="sc">$</span>tuning</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   steps  test train models      lr
   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;    &lt;dbl&gt;
 1     1  321.     0 NA     0.0394 
 2     2  318.     0 NA     0.0623 
 3     3  337.     0 NA     0.0627 
 4     4  323.     0 NA     0.0804 
 5     5  320.     0 NA     0.0658 
 6     6  324.     0 NA     0.0683 
 7     7  317.     0 NA     0.0417 
 8     8  329.     0 NA     0.0667 
 9     9  350.     0 NA     0.00368
10    10  317.     0 NA     0.0818 </code></pre>
</div>
</div>
<!-- ```{r} -->
<!-- library(glmnet) -->
<!-- library(glmnetUtils) -->
<!-- set.seed(42) -->
<!-- cv = 5 -->
<!-- hyper_lambda = runif(20,0, 0.2) -->
<!-- tuning_results =  -->
<!--     sapply(1:length(hyper_lambda), function(k) { -->
<!--         auc_inner = NULL # save results from CV -->
<!--         for(j in 1:cv) { -->
<!--           inner_split = as.integer(cut(1:nrow(data_obs), breaks = cv)) -->
<!--           train_inner = data_obs[inner_split != j, ] -->
<!--           test_inner = data_obs[inner_split == j, ] -->
<!--           model = glmnet(survived~.,data = train_inner, family = "binomial", lambda = hyper_lambda[k]) -->
<!--           auc_inner[j]= Metrics::auc(test_inner$survived, predict(model, test_inner, type = "response")) -->
<!--         } -->
<!--       return(mean(auc_inner)) -->
<!--     }) -->
<!-- results = data.frame(lambda = hyper_lambda, AUC = tuning_results) -->
<!-- print(results) -->
<!-- ``` -->
<!-- The best (highest AUC) $\lambda$ is then: -->
<!-- ```{r} -->
<!-- results[which.max(results$AUC),] -->
<!-- ``` -->
</section>
</section>
<section id="predictions-and-submission" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="predictions-and-submission"><span class="header-section-number">4.3</span> Predictions and Submission</h2>
<p>When we are satisfied with the performance of our model, we will create predictions for the new observations on the submission server. cito directly returns the best model so we do not have to fit the final model.</p>
<p>We submit our predictions to the submission server at <a href="http://rhsbio7.uni-regensburg.de:8500" target="_blank" rel="noopener">http://rhsbio7.uni-regensburg.de:8500</a>.</p>
<p>For the submission it is critical to change the predictions into a data.frame, select the second column (the probability to survive), and save it with the write.csv function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>data_new <span class="ot">=</span> data_sub[<span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),]</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">predict</span>(model, data_new, <span class="at">type =</span> <span class="st">"response"</span>)[,<span class="dv">1</span>] </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="fu">data.frame</span>(<span class="at">y =</span> predictions), <span class="at">file =</span> <span class="st">"Max_1.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercises" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="exercises"><span class="header-section-number">4.4</span> Exercises</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Hyperparameter tuning dnn - Titanic dataset
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tune architecture</p>
<ul>
<li>Tune training parameters (learning rate, batch size) and regularization</li>
</ul>
<p><strong>Hints</strong></p>
<p>cito has a feature to automatically tune hyperparameters under Cross Validation!</p>
<ul>
<li>passing <code>tune(...)</code> to a hyperparameter will tell cito to tune this specific hyperparameter</li>
<li>the <code>tuning = config_tuning(...)</code> let you specify the cross-validation strategy and the number of hyperparameters that should be tested (steps = number of hyperparameter combinations that should be tried)</li>
<li>after tuning, cito will fit automatically a model with the best hyperparameters on the full data and will return this model</li>
</ul>
<p>Minimal example with the iris dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cito)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> iris</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>df[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">=</span> <span class="fu">scale</span>(df[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>model_tuned <span class="ot">=</span> <span class="fu">dnn</span>(Species<span class="sc">~</span>., </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">loss =</span> <span class="st">"softmax"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> iris,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">lambda =</span> <span class="fu">tune</span>(<span class="at">lower =</span> <span class="fl">0.0</span>, <span class="at">upper =</span> <span class="fl">0.2</span>), <span class="co"># you can pass the "tune" function to a hyerparameter</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuning =</span> <span class="fu">config_tuning</span>(<span class="at">CV =</span> <span class="dv">3</span>, <span class="at">steps =</span> <span class="dv">20</span>L)</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>                  )</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a><span class="co"># tuning results</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>model_tuned<span class="sc">$</span>tuning</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a><span class="co"># model_tuned is now already the best model!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EcoData)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(missRanger)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(titanic_ml)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> titanic_ml</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> </span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> <span class="fu">select</span>(survived, sex, age, fare, pclass)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>data[,<span class="sc">-</span><span class="dv">1</span>] <span class="ot">=</span> <span class="fu">missRanger</span>(data[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">verbose =</span> <span class="dv">0</span>)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>data_sub <span class="ot">=</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">age =</span> scales<span class="sc">::</span><span class="fu">rescale</span>(age, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">fare =</span> scales<span class="sc">::</span><span class="fu">rescale</span>(fare, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as.integer</span>(sex) <span class="sc">-</span> <span class="dv">1</span>L,</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">pclass =</span> <span class="fu">as.integer</span>(pclass <span class="sc">-</span> <span class="dv">1</span>L))</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>data_new <span class="ot">=</span> data_sub[<span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] <span class="co"># for which we want to make predictions at the end</span></span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>data_obs <span class="ot">=</span> data_sub[<span class="sc">!</span><span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] <span class="co"># data with known response</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">dnn</span>(survived<span class="sc">~</span>., </span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a>          <span class="at">hidden =</span> <span class="fu">c</span>(<span class="dv">10</span>L, <span class="dv">10</span>L), <span class="co"># change</span></span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a>          <span class="at">activation =</span> <span class="fu">c</span>(<span class="st">"selu"</span>, <span class="st">"selu"</span>), <span class="co"># change</span></span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a>          <span class="at">loss =</span> <span class="st">"binomial"</span>, </span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a>          <span class="at">lr =</span> <span class="fl">0.05</span>, <span class="co">#change</span></span>
<span id="cb49-25"><a href="#cb49-25" aria-hidden="true" tabindex="-1"></a>          <span class="at">validation =</span> <span class="fl">0.2</span>,</span>
<span id="cb49-26"><a href="#cb49-26" aria-hidden="true" tabindex="-1"></a>          <span class="at">lambda =</span> <span class="fl">0.001</span>, <span class="co"># change</span></span>
<span id="cb49-27"><a href="#cb49-27" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="co"># change</span></span>
<span id="cb49-28"><a href="#cb49-28" aria-hidden="true" tabindex="-1"></a>          <span class="at">lr_scheduler =</span> <span class="fu">config_lr_scheduler</span>(<span class="st">"reduce_on_plateau"</span>, <span class="at">patience =</span> <span class="dv">10</span>, <span class="at">factor =</span> <span class="fl">0.9</span>),</span>
<span id="cb49-29"><a href="#cb49-29" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> data_obs, <span class="at">epochs =</span> <span class="dv">40</span>L, <span class="at">verbose =</span> <span class="cn">FALSE</span>, <span class="at">plot=</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="A4-MLpipeline_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions:</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> data_new, <span class="at">type =</span> <span class="st">"response"</span>) <span class="co"># change prediction type to response so that cito predicts probabilities</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="fu">data.frame</span>(<span class="at">y =</span> predictions[,<span class="dv">1</span>]), <span class="at">file =</span> <span class="st">"Max_titanic_dnn.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<!-- ::: {.callout-warning} -->
<!-- #### Task: Tuning $\alpha$ and $\lambda$ -->
<!-- 1.  Extend the code from above and tune $\alpha$ and $\lambda$ (via 10xCV) -->
<!-- 2.  Train the model with best set of hyperparameters and submit your predictions -->
<!-- Submit your predictions (<http://rhsbio7.uni-regensburg.de:8500/>), which model has a higher AUC?. -->
<!-- **Important**: -->
<!-- Submissions only work if your preditions are probabilities and a data.frame (which you can create via `write.csv(data.frame(y = predictions ), file = "Max_1.csv")` -->
<!--  ) -->
<!-- ```{r} -->
<!-- library(EcoData) -->
<!-- library(dplyr) -->
<!-- library(missRanger) -->
<!-- library(glmnet) -->
<!-- library(glmnetUtils) -->
<!-- data(titanic_ml) -->
<!-- data = titanic_ml -->
<!-- data =  -->
<!--   data %>% select(survived, sex, age, fare, pclass) -->
<!-- # missRanger uses a random forest to impute NAs (RF is trained on the data to predict values for the NAs) -->
<!-- data[,-1] = missRanger(data[,-1], verbose = 0) -->
<!-- data_sub = -->
<!--   data %>% -->
<!--     mutate(age = scales::rescale(age, c(0, 1)), -->
<!--            fare = scales::rescale(fare, c(0, 1))) %>% -->
<!--     mutate(sex = as.integer(sex) - 1L, -->
<!--            pclass = as.integer(pclass - 1L)) -->
<!-- data_new = data_sub[is.na(data_sub$survived),] # for which we want to make predictions at the end -->
<!-- data_obs = data_sub[!is.na(data_sub$survived),] # data with known response -->
<!-- ``` -->
<!-- Bonus: -->
<!-- -   Try different features -->
<!-- -   Try cito -->
<!-- -   Try different datasets (see @sec-datasets) -->
<!-- Code template for a simple CV (for tuning $\lambda$): -->
<!-- - Extend the following code so that $\alpha$ is also tuned! -->
<!-- ```{r} -->
<!-- set.seed(42) -->
<!-- cv = 5 -->
<!-- hyper_lambda = runif(20,0, 0.2) -->
<!-- tuning_results = -->
<!--     sapply(1:length(hyper_lambda), function(k) { -->
<!--         auc_inner = NULL -->
<!--         for(j in 1:cv) { -->
<!--           inner_split = as.integer(cut(1:nrow(data_obs), breaks = cv)) -->
<!--           train_inner = data_obs[inner_split != j, ] -->
<!--           test_inner = data_obs[inner_split == j, ] -->
<!--           model = glmnet(survived~.,data = train_inner, lambda = hyper_lambda[k], family = "binomial") -->
<!--           auc_inner[j]= Metrics::auc(test_inner$survived, predict(model, test_inner, type = "response")) -->
<!--         } -->
<!--       return(mean(auc_inner)) -->
<!--     }) -->
<!-- results = data.frame(lambda = hyper_lambda, AUC = tuning_results) -->
<!-- print(results) -->
<!-- ``` -->
<!-- ::: -->
<!-- 
<div class='webex-solution'><button>Click here to see the solution</button>
 -->
<!-- ```{r} -->
<!-- set.seed(42) -->
<!-- cv = 5 -->
<!-- hyper_lambda = runif(20,0, 0.2) -->
<!-- hyper_alpha = runif(20, 0, 1) -->
<!-- tuning_results =  -->
<!--     sapply(1:length(hyper_alpha), function(k) { -->
<!--         auc_inner = NULL -->
<!--         for(j in 1:cv) { -->
<!--           inner_split = as.integer(cut(1:nrow(data_obs), breaks = cv)) -->
<!--           train_inner = data_obs[inner_split != j, ] -->
<!--           test_inner = data_obs[inner_split == j, ] -->
<!--           model = glmnet(survived~.,data = train_inner, family = "binomial", alpha = hyper_alpha[k], lambda = hyper_lambda[k]) -->
<!--           auc_inner[j]= Metrics::auc(test_inner$survived, predict(model, test_inner, type = "response")) -->
<!--         } -->
<!--       return(mean(auc_inner)) -->
<!--     }) -->
<!-- results = data.frame(lambda = hyper_lambda, alpha = hyper_alpha,  AUC = tuning_results) -->
<!-- print(results) -->
<!-- print(results[which.max(results$AUC),]) -->
<!-- ``` -->
<!-- Predictions: -->
<!-- ```{r, results='hide', message=FALSE, warning=FALSE} -->
<!-- model = glmnet(survived~.,data = data_obs, family = "binomial",alpha = results[which.max(results$AUC),2]) -->
<!-- predictions = predict(model, data_new, alpha = results$alpha[i], s = results[which.max(results$AUC),1], type = "response")[,1] -->
<!-- write.csv(data.frame(y = predictions, file = "Max_titanic_best_model.csv")) -->
<!-- ``` -->
<!-- 
</div>
 -->
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Hyperparameter tuning rf
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Hyperparameter</th>
<th>Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>mtry</td>
<td>Subset of features randomly selected in each node (from which the algorithm can select the feature that will be used to split the data).</td>
</tr>
<tr class="even">
<td>minimum node size</td>
<td>Minimal number of observations allowed in a node (before the branching is canceled)</td>
</tr>
<tr class="odd">
<td>max depth</td>
<td>Maximum number of tree depth</td>
</tr>
</tbody>
</table>
<p>Combing back to the titanic dataset from the morning, we want to optimize min node size in our RF using a simple CV.</p>
<p>Prepare the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EcoData)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(missRanger)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(titanic_ml)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> titanic_ml</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> <span class="fu">select</span>(survived, sex, age, fare, pclass)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>data[,<span class="sc">-</span><span class="dv">1</span>] <span class="ot">=</span> <span class="fu">missRanger</span>(data[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">verbose =</span> <span class="dv">0</span>)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>data_sub <span class="ot">=</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">age =</span> scales<span class="sc">::</span><span class="fu">rescale</span>(age, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">fare =</span> scales<span class="sc">::</span><span class="fu">rescale</span>(fare, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as.integer</span>(sex) <span class="sc">-</span> <span class="dv">1</span>L,</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">pclass =</span> <span class="fu">as.integer</span>(pclass <span class="sc">-</span> <span class="dv">1</span>L))</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>data_new <span class="ot">=</span> data_sub[<span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] <span class="co"># for which we want to make predictions at the end</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>data_obs <span class="ot">=</span> data_sub[<span class="sc">!</span><span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] <span class="co"># data with known response</span></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>data_sub<span class="sc">$</span>survived <span class="ot">=</span> <span class="fu">as.factor</span>(data_sub<span class="sc">$</span>survived)</span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>data_obs<span class="sc">$</span>survived <span class="ot">=</span> <span class="fu">as.factor</span>(data_obs<span class="sc">$</span>survived)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Hints:</strong></p>
<ul>
<li>adjust the ‘<code>type</code>’ argument in the <code>predict(…)</code> method (the default is to predict classes)</li>
<li>when predicting probabilities, the randomForest will return a matrix, a column for each class, we are interested in the probability of surviving (so the second column)</li>
</ul>
<p><strong>Bonus:</strong></p>
<ul>
<li>tune min node size (and mtry)</li>
<li>use more features</li>
</ul>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code template
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>data_obs <span class="ot">=</span> data_sub[<span class="sc">!</span><span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">=</span> <span class="dv">3</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>hyper_minnodesize <span class="ot">=</span> ...</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>tuning_results <span class="ot">=</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(hyper_minnodesize), <span class="cf">function</span>(k) {</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>        auc_inner <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>cv) {</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>          inner_split <span class="ot">=</span> <span class="fu">as.integer</span>(<span class="fu">cut</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data_obs), <span class="at">breaks =</span> cv))</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>          train_inner <span class="ot">=</span> data_obs[inner_split <span class="sc">!=</span> j, ]</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>          test_inner <span class="ot">=</span> data_obs[inner_split <span class="sc">==</span> j, ]</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>          model <span class="ot">=</span> <span class="fu">ranger</span>(survived<span class="sc">~</span>.,<span class="at">data =</span> train_inner, <span class="at">min.node.size =</span> hyper_minnodesize[k], <span class="at">probability =</span> <span class="cn">TRUE</span>)</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>          predictions <span class="ot">=</span> <span class="fu">predict</span>(model, test_inner)<span class="sc">$</span>predictions[,<span class="dv">2</span>]</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>          auc_inner[j]<span class="ot">=</span> Metrics<span class="sc">::</span><span class="fu">auc</span>(test_inner<span class="sc">$</span>survived, predictions)</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="fu">mean</span>(auc_inner))</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>results <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">minnodesize =</span> hyper_minnodesize, <span class="at">AUC =</span> tuning_results)</span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="webex-solution">
<button>
Click here to see the solution
</button>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>data_obs <span class="ot">=</span> data_sub[<span class="sc">!</span><span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">=</span> <span class="dv">3</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>hyper_minnodesize <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">300</span>, <span class="dv">20</span>)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>tuning_results <span class="ot">=</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(hyper_minnodesize), <span class="cf">function</span>(k) {</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>        auc_inner <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>cv) {</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>          inner_split <span class="ot">=</span> <span class="fu">as.integer</span>(<span class="fu">cut</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data_obs), <span class="at">breaks =</span> cv))</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>          train_inner <span class="ot">=</span> data_obs[inner_split <span class="sc">!=</span> j, ]</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>          test_inner <span class="ot">=</span> data_obs[inner_split <span class="sc">==</span> j, ]</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>          model <span class="ot">=</span> <span class="fu">ranger</span>(survived<span class="sc">~</span>.,<span class="at">data =</span> train_inner, <span class="at">min.node.size =</span> hyper_minnodesize[k], <span class="at">probability =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>          predictions <span class="ot">=</span> <span class="fu">predict</span>(model, test_inner)<span class="sc">$</span>predictions[,<span class="dv">2</span>]</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>          auc_inner[j]<span class="ot">=</span> Metrics<span class="sc">::</span><span class="fu">auc</span>(test_inner<span class="sc">$</span>survived, predictions)</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="fu">mean</span>(auc_inner))</span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>results <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">minnodesize =</span> hyper_minnodesize, <span class="at">AUC =</span> tuning_results)</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   minnodesize       AUC
1           49 0.8273720
2          153 0.8192129
3           74 0.8201036
4          228 0.8145704
5          146 0.8179711
6          122 0.8199548
7          300 0.8091299
8          128 0.8211871
9           24 0.8317129
10          89 0.8216111
11         165 0.8175560
12         110 0.8198210
13          20 0.8301084
14         291 0.8093610
15         283 0.8099834
16         109 0.8218099
17           5 0.8293107
18         212 0.8136150
19         259 0.8123784
20         292 0.8086269</code></pre>
</div>
</div>
<p>Make predictions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">ranger</span>(survived<span class="sc">~</span>.,<span class="at">data =</span> data_obs, <span class="at">min.node.size =</span> results[<span class="fu">which.max</span>(results<span class="sc">$</span>AUC),<span class="dv">1</span>], <span class="at">probability =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="fu">data.frame</span>(<span class="at">y =</span> <span class="fu">predict</span>(model, data_new)<span class="sc">$</span>predictions[,<span class="dv">1</span>]), <span class="at">file =</span> <span class="st">"Max_titanic_rf.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Hyperparameter tuning BRT
</div>
</div>
<div class="callout-body-container callout-body">
<p>Important hyperparameters:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Hyperparameter</th>
<th>Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>eta</td>
<td>learning rate (weighting of the sequential trees)</td>
</tr>
<tr class="even">
<td>max depth</td>
<td>maximal depth in the trees (small = low complexity, large = high complexity)</td>
</tr>
<tr class="odd">
<td>subsample</td>
<td>subsample ratio of the data (bootstrap ratio)</td>
</tr>
<tr class="even">
<td>lambda</td>
<td>regularization strength of the individual trees</td>
</tr>
<tr class="odd">
<td>max tree</td>
<td>maximal number of trees in the ensemble</td>
</tr>
</tbody>
</table>
<p>Combing back to the titanic dataset from the morning, we want to optimize max depth and the eta parameter in xgboost.</p>
<p>Prepare the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EcoData)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(missRanger)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(titanic_ml)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> titanic_ml</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> <span class="fu">select</span>(survived, sex, age, fare, pclass)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>data[,<span class="sc">-</span><span class="dv">1</span>] <span class="ot">=</span> <span class="fu">missRanger</span>(data[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">verbose =</span> <span class="dv">0</span>)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>data_sub <span class="ot">=</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">age =</span> scales<span class="sc">::</span><span class="fu">rescale</span>(age, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">fare =</span> scales<span class="sc">::</span><span class="fu">rescale</span>(fare, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as.integer</span>(sex) <span class="sc">-</span> <span class="dv">1</span>L,</span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">pclass =</span> <span class="fu">as.integer</span>(pclass <span class="sc">-</span> <span class="dv">1</span>L))</span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>data_new <span class="ot">=</span> data_sub[<span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] <span class="co"># for which we want to make predictions at the end</span></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>data_obs <span class="ot">=</span> data_sub[<span class="sc">!</span><span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] <span class="co"># data with known response</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code template
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xgboost)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>data_obs <span class="ot">=</span> data_sub[<span class="sc">!</span><span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">=</span> <span class="dv">3</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>outer_split <span class="ot">=</span> <span class="fu">as.integer</span>(<span class="fu">cut</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data_obs), <span class="at">breaks =</span> cv))</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="co"># sample minnodesize values (must be integers)</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>hyper_depth <span class="ot">=</span> ...</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>hyper_eta <span class="ot">=</span> ...</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>tuning_results <span class="ot">=</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(hyper_eta), <span class="cf">function</span>(k) {</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>        auc_inner <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>cv) {</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>          inner_split <span class="ot">=</span> <span class="fu">as.integer</span>(<span class="fu">cut</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data_obs), <span class="at">breaks =</span> cv))</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>          train_inner <span class="ot">=</span> data_obs[inner_split <span class="sc">!=</span> j, ]</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>          test_inner <span class="ot">=</span> data_obs[inner_split <span class="sc">==</span> j, ]</span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>          data_xg <span class="ot">=</span> <span class="fu">xgb.DMatrix</span>(<span class="at">data =</span> <span class="fu">as.matrix</span>(train_inner[,<span class="sc">-</span><span class="dv">1</span>]), <span class="at">label =</span> train_inner<span class="sc">$</span>survived)</span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>          model <span class="ot">=</span> <span class="fu">xgboost</span>(data_xg, <span class="at">nrounds =</span> <span class="dv">16</span>L, <span class="at">eta =</span> hyper_eta[k], <span class="at">max_depth =</span> hyper_depth[k], <span class="at">objective =</span> <span class="st">"reg:logistic"</span>)</span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>          predictions <span class="ot">=</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> <span class="fu">as.matrix</span>(test_inner)[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>          auc_inner[j]<span class="ot">=</span> Metrics<span class="sc">::</span><span class="fu">auc</span>(test_inner<span class="sc">$</span>survived, predictions)</span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="fu">mean</span>(auc_inner))</span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a>results <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">depth =</span> hyper_depth, <span class="at">eta =</span> hyper_eta, <span class="at">AUC =</span> tuning_results)</span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="webex-solution">
<button>
Click here to see the solution
</button>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xgboost)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'xgboost'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    slice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>data_obs <span class="ot">=</span> data_sub[<span class="sc">!</span><span class="fu">is.na</span>(data_sub<span class="sc">$</span>survived),] </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">=</span> <span class="dv">3</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>outer_split <span class="ot">=</span> <span class="fu">as.integer</span>(<span class="fu">cut</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data_obs), <span class="at">breaks =</span> cv))</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="co"># sample minnodesize values (must be integers)</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>hyper_depth <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">200</span>, <span class="dv">20</span>)</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>hyper_eta <span class="ot">=</span> <span class="fu">runif</span>(<span class="dv">20</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>tuning_results <span class="ot">=</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(hyper_eta), <span class="cf">function</span>(k) {</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>        auc_inner <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>cv) {</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>          inner_split <span class="ot">=</span> <span class="fu">as.integer</span>(<span class="fu">cut</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data_obs), <span class="at">breaks =</span> cv))</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>          train_inner <span class="ot">=</span> data_obs[inner_split <span class="sc">!=</span> j, ]</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>          test_inner <span class="ot">=</span> data_obs[inner_split <span class="sc">==</span> j, ]</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>          data_xg <span class="ot">=</span> <span class="fu">xgb.DMatrix</span>(<span class="at">data =</span> <span class="fu">as.matrix</span>(train_inner[,<span class="sc">-</span><span class="dv">1</span>]), <span class="at">label =</span> train_inner<span class="sc">$</span>survived)</span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>          model <span class="ot">=</span> <span class="fu">xgboost</span>(data_xg, <span class="at">nrounds =</span> <span class="dv">16</span>L, <span class="at">eta =</span> hyper_eta[k], <span class="at">max_depth =</span> hyper_depth[k], <span class="at">objective =</span> <span class="st">"reg:logistic"</span>)</span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>          predictions <span class="ot">=</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> <span class="fu">as.matrix</span>(test_inner)[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>          </span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>          auc_inner[j]<span class="ot">=</span> Metrics<span class="sc">::</span><span class="fu">auc</span>(test_inner<span class="sc">$</span>survived, predictions)</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="fu">mean</span>(auc_inner))</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>    })</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] train-rmse:0.342302 
[2] train-rmse:0.296557 
[3] train-rmse:0.263769 
[4] train-rmse:0.241327 
[5] train-rmse:0.217183 
[6] train-rmse:0.201909 
[7] train-rmse:0.189654 
[8] train-rmse:0.183617 
[9] train-rmse:0.173235 
[10]    train-rmse:0.166394 
[11]    train-rmse:0.161046 
[12]    train-rmse:0.155769 
[13]    train-rmse:0.151022 
[14]    train-rmse:0.147104 
[15]    train-rmse:0.144162 
[16]    train-rmse:0.140758 
[1] train-rmse:0.354493 
[2] train-rmse:0.305145 
[3] train-rmse:0.275617 
[4] train-rmse:0.256898 
[5] train-rmse:0.236243 
[6] train-rmse:0.225320 
[7] train-rmse:0.216780 
[8] train-rmse:0.206392 
[9] train-rmse:0.200376 
[10]    train-rmse:0.192735 
[11]    train-rmse:0.185090 
[12]    train-rmse:0.179520 
[13]    train-rmse:0.173707 
[14]    train-rmse:0.171483 
[15]    train-rmse:0.167530 
[16]    train-rmse:0.164484 
[1] train-rmse:0.353920 
[2] train-rmse:0.315997 
[3] train-rmse:0.290410 
[4] train-rmse:0.263742 
[5] train-rmse:0.247020 
[6] train-rmse:0.229175 
[7] train-rmse:0.214455 
[8] train-rmse:0.199326 
[9] train-rmse:0.194674 
[10]    train-rmse:0.184985 
[11]    train-rmse:0.180155 
[12]    train-rmse:0.174841 
[13]    train-rmse:0.170210 
[14]    train-rmse:0.165885 
[15]    train-rmse:0.162765 
[16]    train-rmse:0.157283 
[1] train-rmse:0.344811 
[2] train-rmse:0.300368 
[3] train-rmse:0.266761 
[4] train-rmse:0.237761 
[5] train-rmse:0.220317 
[6] train-rmse:0.207316 
[7] train-rmse:0.198329 
[8] train-rmse:0.188430 
[9] train-rmse:0.183203 
[10]    train-rmse:0.176577 
[11]    train-rmse:0.169758 
[12]    train-rmse:0.163186 
[13]    train-rmse:0.157300 
[14]    train-rmse:0.153470 
[15]    train-rmse:0.147181 
[16]    train-rmse:0.144844 
[1] train-rmse:0.356759 
[2] train-rmse:0.304838 
[3] train-rmse:0.274020 
[4] train-rmse:0.255291 
[5] train-rmse:0.243225 
[6] train-rmse:0.229671 
[7] train-rmse:0.219460 
[8] train-rmse:0.206061 
[9] train-rmse:0.197987 
[10]    train-rmse:0.188549 
[11]    train-rmse:0.182957 
[12]    train-rmse:0.177919 
[13]    train-rmse:0.175019 
[14]    train-rmse:0.170526 
[15]    train-rmse:0.166915 
[16]    train-rmse:0.162403 
[1] train-rmse:0.356097 
[2] train-rmse:0.317622 
[3] train-rmse:0.292497 
[4] train-rmse:0.273470 
[5] train-rmse:0.254577 
[6] train-rmse:0.240930 
[7] train-rmse:0.231185 
[8] train-rmse:0.216655 
[9] train-rmse:0.206242 
[10]    train-rmse:0.197043 
[11]    train-rmse:0.189754 
[12]    train-rmse:0.181673 
[13]    train-rmse:0.176834 
[14]    train-rmse:0.171924 
[15]    train-rmse:0.167137 
[16]    train-rmse:0.162462 
[1] train-rmse:0.479481 
[2] train-rmse:0.461296 
[3] train-rmse:0.444451 
[4] train-rmse:0.429059 
[5] train-rmse:0.415414 
[6] train-rmse:0.402186 
[7] train-rmse:0.390414 
[8] train-rmse:0.379435 
[9] train-rmse:0.369452 
[10]    train-rmse:0.360190 
[11]    train-rmse:0.351835 
[12]    train-rmse:0.344269 
[13]    train-rmse:0.336940 
[14]    train-rmse:0.330170 
[15]    train-rmse:0.324636 
[16]    train-rmse:0.319224 
[1] train-rmse:0.480872 
[2] train-rmse:0.463671 
[3] train-rmse:0.446699 
[4] train-rmse:0.431160 
[5] train-rmse:0.417340 
[6] train-rmse:0.404995 
[7] train-rmse:0.394284 
[8] train-rmse:0.384497 
[9] train-rmse:0.375554 
[10]    train-rmse:0.367333 
[11]    train-rmse:0.359942 
[12]    train-rmse:0.352282 
[13]    train-rmse:0.346492 
[14]    train-rmse:0.341002 
[15]    train-rmse:0.335982 
[16]    train-rmse:0.331736 
[1] train-rmse:0.480609 
[2] train-rmse:0.463264 
[3] train-rmse:0.447044 
[4] train-rmse:0.432491 
[5] train-rmse:0.419710 
[6] train-rmse:0.407421 
[7] train-rmse:0.396677 
[8] train-rmse:0.386282 
[9] train-rmse:0.377689 
[10]    train-rmse:0.369330 
[11]    train-rmse:0.361271 
[12]    train-rmse:0.353993 
[13]    train-rmse:0.347109 
[14]    train-rmse:0.340902 
[15]    train-rmse:0.335439 
[16]    train-rmse:0.330551 
[1] train-rmse:0.391331 
[2] train-rmse:0.336196 
[3] train-rmse:0.305060 
[4] train-rmse:0.283270 
[5] train-rmse:0.265297 
[6] train-rmse:0.253524 
[7] train-rmse:0.241562 
[8] train-rmse:0.229415 
[9] train-rmse:0.216797 
[10]    train-rmse:0.209464 
[11]    train-rmse:0.201144 
[12]    train-rmse:0.195527 
[13]    train-rmse:0.191203 
[14]    train-rmse:0.185738 
[15]    train-rmse:0.182161 
[16]    train-rmse:0.177461 
[1] train-rmse:0.399304 
[2] train-rmse:0.347299 
[3] train-rmse:0.315269 
[4] train-rmse:0.294179 
[5] train-rmse:0.280553 
[6] train-rmse:0.267001 
[7] train-rmse:0.251934 
[8] train-rmse:0.244570 
[9] train-rmse:0.236971 
[10]    train-rmse:0.229536 
[11]    train-rmse:0.224027 
[12]    train-rmse:0.218198 
[13]    train-rmse:0.214238 
[14]    train-rmse:0.208287 
[15]    train-rmse:0.205090 
[16]    train-rmse:0.200239 
[1] train-rmse:0.398243 
[2] train-rmse:0.350427 
[3] train-rmse:0.321054 
[4] train-rmse:0.303792 
[5] train-rmse:0.288216 
[6] train-rmse:0.274223 
[7] train-rmse:0.263454 
[8] train-rmse:0.252615 
[9] train-rmse:0.245005 
[10]    train-rmse:0.234036 
[11]    train-rmse:0.225401 
[12]    train-rmse:0.218698 
[13]    train-rmse:0.213294 
[14]    train-rmse:0.208168 
[15]    train-rmse:0.202857 
[16]    train-rmse:0.196321 
[1] train-rmse:0.412613 
[2] train-rmse:0.358420 
[3] train-rmse:0.326669 
[4] train-rmse:0.303319 
[5] train-rmse:0.286022 
[6] train-rmse:0.273749 
[7] train-rmse:0.263153 
[8] train-rmse:0.251950 
[9] train-rmse:0.243505 
[10]    train-rmse:0.236474 
[11]    train-rmse:0.228569 
[12]    train-rmse:0.221599 
[13]    train-rmse:0.212299 
[14]    train-rmse:0.205074 
[15]    train-rmse:0.200964 
[16]    train-rmse:0.194888 
[1] train-rmse:0.418903 
[2] train-rmse:0.368349 
[3] train-rmse:0.335454 
[4] train-rmse:0.314156 
[5] train-rmse:0.298537 
[6] train-rmse:0.284029 
[7] train-rmse:0.273099 
[8] train-rmse:0.263954 
[9] train-rmse:0.252246 
[10]    train-rmse:0.244578 
[11]    train-rmse:0.239407 
[12]    train-rmse:0.234422 
[13]    train-rmse:0.228069 
[14]    train-rmse:0.223888 
[15]    train-rmse:0.218094 
[16]    train-rmse:0.215078 
[1] train-rmse:0.417948 
[2] train-rmse:0.367809 
[3] train-rmse:0.336307 
[4] train-rmse:0.314008 
[5] train-rmse:0.297239 
[6] train-rmse:0.285473 
[7] train-rmse:0.275437 
[8] train-rmse:0.266708 
[9] train-rmse:0.258052 
[10]    train-rmse:0.250290 
[11]    train-rmse:0.242443 
[12]    train-rmse:0.236872 
[13]    train-rmse:0.229573 
[14]    train-rmse:0.224046 
[15]    train-rmse:0.219750 
[16]    train-rmse:0.214634 
[1] train-rmse:0.347540 
[2] train-rmse:0.303626 
[3] train-rmse:0.272683 
[4] train-rmse:0.243109 
[5] train-rmse:0.223824 
[6] train-rmse:0.210663 
[7] train-rmse:0.199044 
[8] train-rmse:0.188770 
[9] train-rmse:0.178904 
[10]    train-rmse:0.173196 
[11]    train-rmse:0.167350 
[12]    train-rmse:0.163099 
[13]    train-rmse:0.155632 
[14]    train-rmse:0.152195 
[15]    train-rmse:0.147318 
[16]    train-rmse:0.144478 
[1] train-rmse:0.359231 
[2] train-rmse:0.308544 
[3] train-rmse:0.278949 
[4] train-rmse:0.256349 
[5] train-rmse:0.241120 
[6] train-rmse:0.227070 
[7] train-rmse:0.217868 
[8] train-rmse:0.206924 
[9] train-rmse:0.202159 
[10]    train-rmse:0.193935 
[11]    train-rmse:0.187499 
[12]    train-rmse:0.182944 
[13]    train-rmse:0.179975 
[14]    train-rmse:0.174656 
[15]    train-rmse:0.171647 
[16]    train-rmse:0.168707 
[1] train-rmse:0.358490 
[2] train-rmse:0.315554 
[3] train-rmse:0.288114 
[4] train-rmse:0.262765 
[5] train-rmse:0.247720 
[6] train-rmse:0.236217 
[7] train-rmse:0.219483 
[8] train-rmse:0.206180 
[9] train-rmse:0.198773 
[10]    train-rmse:0.190334 
[11]    train-rmse:0.184461 
[12]    train-rmse:0.178594 
[13]    train-rmse:0.173868 
[14]    train-rmse:0.170536 
[15]    train-rmse:0.166593 
[16]    train-rmse:0.163310 
[1] train-rmse:0.402424 
[2] train-rmse:0.346928 
[3] train-rmse:0.314267 
[4] train-rmse:0.293571 
[5] train-rmse:0.275489 
[6] train-rmse:0.263132 
[7] train-rmse:0.249888 
[8] train-rmse:0.239288 
[9] train-rmse:0.233887 
[10]    train-rmse:0.224376 
[11]    train-rmse:0.215130 
[12]    train-rmse:0.209099 
[13]    train-rmse:0.201128 
[14]    train-rmse:0.194383 
[15]    train-rmse:0.190227 
[16]    train-rmse:0.185943 
[1] train-rmse:0.409511 
[2] train-rmse:0.357163 
[3] train-rmse:0.324910 
[4] train-rmse:0.303323 
[5] train-rmse:0.286659 
[6] train-rmse:0.275220 
[7] train-rmse:0.265906 
[8] train-rmse:0.253159 
[9] train-rmse:0.246518 
[10]    train-rmse:0.237044 
[11]    train-rmse:0.231812 
[12]    train-rmse:0.224940 
[13]    train-rmse:0.220676 
[14]    train-rmse:0.216981 
[15]    train-rmse:0.213305 
[16]    train-rmse:0.209319 
[1] train-rmse:0.408495 
[2] train-rmse:0.360470 
[3] train-rmse:0.327066 
[4] train-rmse:0.305746 
[5] train-rmse:0.292335 
[6] train-rmse:0.280373 
[7] train-rmse:0.270363 
[8] train-rmse:0.262649 
[9] train-rmse:0.254465 
[10]    train-rmse:0.244795 
[11]    train-rmse:0.238356 
[12]    train-rmse:0.228929 
[13]    train-rmse:0.223343 
[14]    train-rmse:0.218370 
[15]    train-rmse:0.212266 
[16]    train-rmse:0.208432 
[1] train-rmse:0.352912 
[2] train-rmse:0.309031 
[3] train-rmse:0.277692 
[4] train-rmse:0.256625 
[5] train-rmse:0.235777 
[6] train-rmse:0.214268 
[7] train-rmse:0.199580 
[8] train-rmse:0.194155 
[9] train-rmse:0.185362 
[10]    train-rmse:0.177677 
[11]    train-rmse:0.171369 
[12]    train-rmse:0.168394 
[13]    train-rmse:0.159508 
[14]    train-rmse:0.156477 
[15]    train-rmse:0.150386 
[16]    train-rmse:0.147333 
[1] train-rmse:0.364115 
[2] train-rmse:0.312819 
[3] train-rmse:0.281496 
[4] train-rmse:0.257388 
[5] train-rmse:0.240136 
[6] train-rmse:0.226296 
[7] train-rmse:0.219283 
[8] train-rmse:0.210615 
[9] train-rmse:0.203212 
[10]    train-rmse:0.196874 
[11]    train-rmse:0.190957 
[12]    train-rmse:0.186694 
[13]    train-rmse:0.181710 
[14]    train-rmse:0.178089 
[15]    train-rmse:0.173809 
[16]    train-rmse:0.170155 
[1] train-rmse:0.363254 
[2] train-rmse:0.319160 
[3] train-rmse:0.294411 
[4] train-rmse:0.273299 
[5] train-rmse:0.251156 
[6] train-rmse:0.240591 
[7] train-rmse:0.228331 
[8] train-rmse:0.217241 
[9] train-rmse:0.211002 
[10]    train-rmse:0.201419 
[11]    train-rmse:0.193850 
[12]    train-rmse:0.186100 
[13]    train-rmse:0.181138 
[14]    train-rmse:0.174777 
[15]    train-rmse:0.171032 
[16]    train-rmse:0.166749 
[1] train-rmse:0.362176 
[2] train-rmse:0.314899 
[3] train-rmse:0.283499 
[4] train-rmse:0.263383 
[5] train-rmse:0.239849 
[6] train-rmse:0.226875 
[7] train-rmse:0.212486 
[8] train-rmse:0.205695 
[9] train-rmse:0.195985 
[10]    train-rmse:0.191229 
[11]    train-rmse:0.179409 
[12]    train-rmse:0.172459 
[13]    train-rmse:0.167844 
[14]    train-rmse:0.164455 
[15]    train-rmse:0.159117 
[16]    train-rmse:0.156624 
[1] train-rmse:0.372569 
[2] train-rmse:0.326729 
[3] train-rmse:0.298524 
[4] train-rmse:0.276214 
[5] train-rmse:0.259725 
[6] train-rmse:0.246788 
[7] train-rmse:0.235435 
[8] train-rmse:0.225300 
[9] train-rmse:0.215375 
[10]    train-rmse:0.209135 
[11]    train-rmse:0.203847 
[12]    train-rmse:0.199532 
[13]    train-rmse:0.193989 
[14]    train-rmse:0.188594 
[15]    train-rmse:0.184746 
[16]    train-rmse:0.181138 
[1] train-rmse:0.371580 
[2] train-rmse:0.328379 
[3] train-rmse:0.303459 
[4] train-rmse:0.279450 
[5] train-rmse:0.260896 
[6] train-rmse:0.243199 
[7] train-rmse:0.233772 
[8] train-rmse:0.227453 
[9] train-rmse:0.217446 
[10]    train-rmse:0.211120 
[11]    train-rmse:0.203136 
[12]    train-rmse:0.196808 
[13]    train-rmse:0.190861 
[14]    train-rmse:0.185876 
[15]    train-rmse:0.180722 
[16]    train-rmse:0.175697 
[1] train-rmse:0.355068 
[2] train-rmse:0.310701 
[3] train-rmse:0.278834 
[4] train-rmse:0.259903 
[5] train-rmse:0.238338 
[6] train-rmse:0.218278 
[7] train-rmse:0.206588 
[8] train-rmse:0.193913 
[9] train-rmse:0.188071 
[10]    train-rmse:0.182172 
[11]    train-rmse:0.177608 
[12]    train-rmse:0.172018 
[13]    train-rmse:0.165400 
[14]    train-rmse:0.161438 
[15]    train-rmse:0.157206 
[16]    train-rmse:0.149544 
[1] train-rmse:0.366080 
[2] train-rmse:0.314497 
[3] train-rmse:0.283504 
[4] train-rmse:0.258938 
[5] train-rmse:0.244948 
[6] train-rmse:0.231373 
[7] train-rmse:0.221023 
[8] train-rmse:0.213963 
[9] train-rmse:0.205689 
[10]    train-rmse:0.199176 
[11]    train-rmse:0.194188 
[12]    train-rmse:0.189800 
[13]    train-rmse:0.183892 
[14]    train-rmse:0.179431 
[15]    train-rmse:0.175402 
[16]    train-rmse:0.173047 
[1] train-rmse:0.365181 
[2] train-rmse:0.320673 
[3] train-rmse:0.296988 
[4] train-rmse:0.271807 
[5] train-rmse:0.249580 
[6] train-rmse:0.237423 
[7] train-rmse:0.222919 
[8] train-rmse:0.213172 
[9] train-rmse:0.205728 
[10]    train-rmse:0.197945 
[11]    train-rmse:0.192628 
[12]    train-rmse:0.184720 
[13]    train-rmse:0.180063 
[14]    train-rmse:0.174582 
[15]    train-rmse:0.170291 
[16]    train-rmse:0.166534 
[1] train-rmse:0.413003 
[2] train-rmse:0.358879 
[3] train-rmse:0.327087 
[4] train-rmse:0.303711 
[5] train-rmse:0.286390 
[6] train-rmse:0.274090 
[7] train-rmse:0.260314 
[8] train-rmse:0.249955 
[9] train-rmse:0.241820 
[10]    train-rmse:0.234428 
[11]    train-rmse:0.226885 
[12]    train-rmse:0.219616 
[13]    train-rmse:0.212639 
[14]    train-rmse:0.207428 
[15]    train-rmse:0.203291 
[16]    train-rmse:0.197492 
[1] train-rmse:0.419262 
[2] train-rmse:0.368771 
[3] train-rmse:0.335856 
[4] train-rmse:0.314520 
[5] train-rmse:0.298882 
[6] train-rmse:0.284372 
[7] train-rmse:0.272740 
[8] train-rmse:0.264158 
[9] train-rmse:0.256454 
[10]    train-rmse:0.246102 
[11]    train-rmse:0.239338 
[12]    train-rmse:0.234446 
[13]    train-rmse:0.228276 
[14]    train-rmse:0.223703 
[15]    train-rmse:0.219541 
[16]    train-rmse:0.216816 
[1] train-rmse:0.418311 
[2] train-rmse:0.368219 
[3] train-rmse:0.336701 
[4] train-rmse:0.314359 
[5] train-rmse:0.297552 
[6] train-rmse:0.285764 
[7] train-rmse:0.275737 
[8] train-rmse:0.267016 
[9] train-rmse:0.258368 
[10]    train-rmse:0.251282 
[11]    train-rmse:0.245400 
[12]    train-rmse:0.237171 
[13]    train-rmse:0.231113 
[14]    train-rmse:0.223861 
[15]    train-rmse:0.219796 
[16]    train-rmse:0.215306 
[1] train-rmse:0.367975 
[2] train-rmse:0.319321 
[3] train-rmse:0.287144 
[4] train-rmse:0.262513 
[5] train-rmse:0.247351 
[6] train-rmse:0.231291 
[7] train-rmse:0.223033 
[8] train-rmse:0.209622 
[9] train-rmse:0.200868 
[10]    train-rmse:0.191819 
[11]    train-rmse:0.182173 
[12]    train-rmse:0.178936 
[13]    train-rmse:0.174043 
[14]    train-rmse:0.171584 
[15]    train-rmse:0.167346 
[16]    train-rmse:0.162605 
[1] train-rmse:0.377873 
[2] train-rmse:0.317379 
[3] train-rmse:0.292246 
[4] train-rmse:0.273028 
[5] train-rmse:0.257528 
[6] train-rmse:0.247641 
[7] train-rmse:0.233587 
[8] train-rmse:0.225675 
[9] train-rmse:0.217171 
[10]    train-rmse:0.211252 
[11]    train-rmse:0.205052 
[12]    train-rmse:0.198105 
[13]    train-rmse:0.193092 
[14]    train-rmse:0.190016 
[15]    train-rmse:0.185144 
[16]    train-rmse:0.181247 
[1] train-rmse:0.376839 
[2] train-rmse:0.330142 
[3] train-rmse:0.304843 
[4] train-rmse:0.287958 
[5] train-rmse:0.273168 
[6] train-rmse:0.258587 
[7] train-rmse:0.243581 
[8] train-rmse:0.231554 
[9] train-rmse:0.223641 
[10]    train-rmse:0.214984 
[11]    train-rmse:0.206594 
[12]    train-rmse:0.200954 
[13]    train-rmse:0.195729 
[14]    train-rmse:0.192239 
[15]    train-rmse:0.187588 
[16]    train-rmse:0.181316 
[1] train-rmse:0.499000 
[2] train-rmse:0.498010 
[3] train-rmse:0.497026 
[4] train-rmse:0.496047 
[5] train-rmse:0.495073 
[6] train-rmse:0.494104 
[7] train-rmse:0.493140 
[8] train-rmse:0.492181 
[9] train-rmse:0.491226 
[10]    train-rmse:0.490275 
[11]    train-rmse:0.489330 
[12]    train-rmse:0.488389 
[13]    train-rmse:0.487453 
[14]    train-rmse:0.486522 
[15]    train-rmse:0.485596 
[16]    train-rmse:0.484675 
[1] train-rmse:0.499066 
[2] train-rmse:0.498148 
[3] train-rmse:0.497234 
[4] train-rmse:0.496325 
[5] train-rmse:0.495422 
[6] train-rmse:0.494523 
[7] train-rmse:0.493629 
[8] train-rmse:0.492739 
[9] train-rmse:0.491855 
[10]    train-rmse:0.490975 
[11]    train-rmse:0.490100 
[12]    train-rmse:0.489230 
[13]    train-rmse:0.488364 
[14]    train-rmse:0.487503 
[15]    train-rmse:0.486647 
[16]    train-rmse:0.485795 
[1] train-rmse:0.499053 
[2] train-rmse:0.498134 
[3] train-rmse:0.497183 
[4] train-rmse:0.496237 
[5] train-rmse:0.495290 
[6] train-rmse:0.494354 
[7] train-rmse:0.493465 
[8] train-rmse:0.492519 
[9] train-rmse:0.491570 
[10]    train-rmse:0.490634 
[11]    train-rmse:0.489702 
[12]    train-rmse:0.488775 
[13]    train-rmse:0.487852 
[14]    train-rmse:0.486929 
[15]    train-rmse:0.486016 
[16]    train-rmse:0.485108 
[1] train-rmse:0.353172 
[2] train-rmse:0.309652 
[3] train-rmse:0.279091 
[4] train-rmse:0.254916 
[5] train-rmse:0.236239 
[6] train-rmse:0.223144 
[7] train-rmse:0.205658 
[8] train-rmse:0.195707 
[9] train-rmse:0.186813 
[10]    train-rmse:0.178283 
[11]    train-rmse:0.172189 
[12]    train-rmse:0.166345 
[13]    train-rmse:0.161567 
[14]    train-rmse:0.155295 
[15]    train-rmse:0.153612 
[16]    train-rmse:0.150238 
[1] train-rmse:0.364352 
[2] train-rmse:0.313021 
[3] train-rmse:0.281973 
[4] train-rmse:0.257413 
[5] train-rmse:0.243398 
[6] train-rmse:0.231083 
[7] train-rmse:0.221349 
[8] train-rmse:0.213183 
[9] train-rmse:0.206201 
[10]    train-rmse:0.197767 
[11]    train-rmse:0.191407 
[12]    train-rmse:0.187852 
[13]    train-rmse:0.184400 
[14]    train-rmse:0.179506 
[15]    train-rmse:0.176823 
[16]    train-rmse:0.173508 
[1] train-rmse:0.363486 
[2] train-rmse:0.319342 
[3] train-rmse:0.294568 
[4] train-rmse:0.273495 
[5] train-rmse:0.251407 
[6] train-rmse:0.240850 
[7] train-rmse:0.228615 
[8] train-rmse:0.217545 
[9] train-rmse:0.211308 
[10]    train-rmse:0.201726 
[11]    train-rmse:0.194161 
[12]    train-rmse:0.186420 
[13]    train-rmse:0.181458 
[14]    train-rmse:0.175103 
[15]    train-rmse:0.171353 
[16]    train-rmse:0.167058 
[1] train-rmse:0.498143 
[2] train-rmse:0.496315 
[3] train-rmse:0.494504 
[4] train-rmse:0.492711 
[5] train-rmse:0.490936 
[6] train-rmse:0.489174 
[7] train-rmse:0.487429 
[8] train-rmse:0.485702 
[9] train-rmse:0.483991 
[10]    train-rmse:0.482297 
[11]    train-rmse:0.480619 
[12]    train-rmse:0.478958 
[13]    train-rmse:0.477314 
[14]    train-rmse:0.475685 
[15]    train-rmse:0.474073 
[16]    train-rmse:0.472476 
[1] train-rmse:0.498267 
[2] train-rmse:0.496570 
[3] train-rmse:0.494890 
[4] train-rmse:0.493226 
[5] train-rmse:0.491580 
[6] train-rmse:0.489950 
[7] train-rmse:0.488336 
[8] train-rmse:0.486738 
[9] train-rmse:0.485157 
[10]    train-rmse:0.483591 
[11]    train-rmse:0.482041 
[12]    train-rmse:0.480509 
[13]    train-rmse:0.478952 
[14]    train-rmse:0.477410 
[15]    train-rmse:0.475883 
[16]    train-rmse:0.474411 
[1] train-rmse:0.498243 
[2] train-rmse:0.496476 
[3] train-rmse:0.494727 
[4] train-rmse:0.493062 
[5] train-rmse:0.491346 
[6] train-rmse:0.489608 
[7] train-rmse:0.487887 
[8] train-rmse:0.486183 
[9] train-rmse:0.484496 
[10]    train-rmse:0.482825 
[11]    train-rmse:0.481171 
[12]    train-rmse:0.479533 
[13]    train-rmse:0.477911 
[14]    train-rmse:0.476288 
[15]    train-rmse:0.474681 
[16]    train-rmse:0.473104 
[1] train-rmse:0.450145 
[2] train-rmse:0.412640 
[3] train-rmse:0.381502 
[4] train-rmse:0.356750 
[5] train-rmse:0.339371 
[6] train-rmse:0.323218 
[7] train-rmse:0.310643 
[8] train-rmse:0.300609 
[9] train-rmse:0.290099 
[10]    train-rmse:0.282061 
[11]    train-rmse:0.274355 
[12]    train-rmse:0.266716 
[13]    train-rmse:0.261058 
[14]    train-rmse:0.254808 
[15]    train-rmse:0.249140 
[16]    train-rmse:0.245194 
[1] train-rmse:0.453614 
[2] train-rmse:0.419638 
[3] train-rmse:0.389756 
[4] train-rmse:0.367082 
[5] train-rmse:0.347280 
[6] train-rmse:0.334347 
[7] train-rmse:0.321853 
[8] train-rmse:0.312025 
[9] train-rmse:0.302219 
[10]    train-rmse:0.294317 
[11]    train-rmse:0.287712 
[12]    train-rmse:0.280739 
[13]    train-rmse:0.275178 
[14]    train-rmse:0.270555 
[15]    train-rmse:0.265659 
[16]    train-rmse:0.261061 
[1] train-rmse:0.453005 
[2] train-rmse:0.416664 
[3] train-rmse:0.389075 
[4] train-rmse:0.367094 
[5] train-rmse:0.348915 
[6] train-rmse:0.334227 
[7] train-rmse:0.322698 
[8] train-rmse:0.312483 
[9] train-rmse:0.305062 
[10]    train-rmse:0.297309 
[11]    train-rmse:0.291410 
[12]    train-rmse:0.285525 
[13]    train-rmse:0.279639 
[14]    train-rmse:0.274354 
[15]    train-rmse:0.269579 
[16]    train-rmse:0.266029 
[1] train-rmse:0.347479 
[2] train-rmse:0.303578 
[3] train-rmse:0.272632 
[4] train-rmse:0.243045 
[5] train-rmse:0.223750 
[6] train-rmse:0.210591 
[7] train-rmse:0.198969 
[8] train-rmse:0.188693 
[9] train-rmse:0.178825 
[10]    train-rmse:0.173116 
[11]    train-rmse:0.167271 
[12]    train-rmse:0.163023 
[13]    train-rmse:0.155557 
[14]    train-rmse:0.152120 
[15]    train-rmse:0.147244 
[16]    train-rmse:0.144406 
[1] train-rmse:0.359176 
[2] train-rmse:0.308494 
[3] train-rmse:0.278888 
[4] train-rmse:0.256292 
[5] train-rmse:0.241052 
[6] train-rmse:0.226995 
[7] train-rmse:0.218274 
[8] train-rmse:0.209522 
[9] train-rmse:0.199627 
[10]    train-rmse:0.192022 
[11]    train-rmse:0.186685 
[12]    train-rmse:0.182298 
[13]    train-rmse:0.178081 
[14]    train-rmse:0.172377 
[15]    train-rmse:0.168291 
[16]    train-rmse:0.165210 
[1] train-rmse:0.358436 
[2] train-rmse:0.315512 
[3] train-rmse:0.288076 
[4] train-rmse:0.262708 
[5] train-rmse:0.247654 
[6] train-rmse:0.236151 
[7] train-rmse:0.219405 
[8] train-rmse:0.206097 
[9] train-rmse:0.198689 
[10]    train-rmse:0.190249 
[11]    train-rmse:0.184376 
[12]    train-rmse:0.178509 
[13]    train-rmse:0.173784 
[14]    train-rmse:0.170455 
[15]    train-rmse:0.166512 
[16]    train-rmse:0.163231 
[1] train-rmse:0.377154 
[2] train-rmse:0.324208 
[3] train-rmse:0.292133 
[4] train-rmse:0.271497 
[5] train-rmse:0.257482 
[6] train-rmse:0.242916 
[7] train-rmse:0.231218 
[8] train-rmse:0.219051 
[9] train-rmse:0.209261 
[10]    train-rmse:0.198130 
[11]    train-rmse:0.191151 
[12]    train-rmse:0.187403 
[13]    train-rmse:0.182459 
[14]    train-rmse:0.174673 
[15]    train-rmse:0.171358 
[16]    train-rmse:0.166835 
[1] train-rmse:0.386284 
[2] train-rmse:0.332859 
[3] train-rmse:0.303453 
[4] train-rmse:0.282584 
[5] train-rmse:0.267558 
[6] train-rmse:0.253924 
[7] train-rmse:0.243237 
[8] train-rmse:0.233537 
[9] train-rmse:0.228959 
[10]    train-rmse:0.220471 
[11]    train-rmse:0.216135 
[12]    train-rmse:0.209025 
[13]    train-rmse:0.204661 
[14]    train-rmse:0.199754 
[15]    train-rmse:0.193463 
[16]    train-rmse:0.190947 
[1] train-rmse:0.385215 
[2] train-rmse:0.338777 
[3] train-rmse:0.313665 
[4] train-rmse:0.292796 
[5] train-rmse:0.273568 
[6] train-rmse:0.262789 
[7] train-rmse:0.253421 
[8] train-rmse:0.239860 
[9] train-rmse:0.231593 
[10]    train-rmse:0.222955 
[11]    train-rmse:0.214456 
[12]    train-rmse:0.209434 
[13]    train-rmse:0.203434 
[14]    train-rmse:0.196974 
[15]    train-rmse:0.192222 
[16]    train-rmse:0.187100 
[1] train-rmse:0.414606 
[2] train-rmse:0.360780 
[3] train-rmse:0.328471 
[4] train-rmse:0.305099 
[5] train-rmse:0.287631 
[6] train-rmse:0.273785 
[7] train-rmse:0.263390 
[8] train-rmse:0.251786 
[9] train-rmse:0.242704 
[10]    train-rmse:0.236481 
[11]    train-rmse:0.229636 
[12]    train-rmse:0.224726 
[13]    train-rmse:0.216931 
[14]    train-rmse:0.211102 
[15]    train-rmse:0.204097 
[16]    train-rmse:0.199598 
[1] train-rmse:0.420741 
[2] train-rmse:0.370518 
[3] train-rmse:0.337584 
[4] train-rmse:0.315976 
[5] train-rmse:0.300921 
[6] train-rmse:0.287629 
[7] train-rmse:0.275361 
[8] train-rmse:0.267142 
[9] train-rmse:0.257956 
[10]    train-rmse:0.250070 
[11]    train-rmse:0.243369 
[12]    train-rmse:0.237665 
[13]    train-rmse:0.233758 
[14]    train-rmse:0.226786 
[15]    train-rmse:0.222565 
[16]    train-rmse:0.218776 
[1] train-rmse:0.419801 
[2] train-rmse:0.369922 
[3] train-rmse:0.338655 
[4] train-rmse:0.317072 
[5] train-rmse:0.301808 
[6] train-rmse:0.290401 
[7] train-rmse:0.281845 
[8] train-rmse:0.272699 
[9] train-rmse:0.263939 
[10]    train-rmse:0.255474 
[11]    train-rmse:0.249697 
[12]    train-rmse:0.244840 
[13]    train-rmse:0.236976 
[14]    train-rmse:0.230660 
[15]    train-rmse:0.227605 
[16]    train-rmse:0.221605 
[1] train-rmse:0.404374 
[2] train-rmse:0.349048 
[3] train-rmse:0.316196 
[4] train-rmse:0.295271 
[5] train-rmse:0.277377 
[6] train-rmse:0.265640 
[7] train-rmse:0.252072 
[8] train-rmse:0.242512 
[9] train-rmse:0.235533 
[10]    train-rmse:0.227548 
[11]    train-rmse:0.218565 
[12]    train-rmse:0.210250 
[13]    train-rmse:0.205741 
[14]    train-rmse:0.201760 
[15]    train-rmse:0.195132 
[16]    train-rmse:0.191336 
[1] train-rmse:0.411308 
[2] train-rmse:0.359166 
[3] train-rmse:0.326783 
[4] train-rmse:0.304912 
[5] train-rmse:0.290269 
[6] train-rmse:0.279429 
[7] train-rmse:0.268528 
[8] train-rmse:0.256203 
[9] train-rmse:0.246645 
[10]    train-rmse:0.240052 
[11]    train-rmse:0.233840 
[12]    train-rmse:0.228318 
[13]    train-rmse:0.223129 
[14]    train-rmse:0.218653 
[15]    train-rmse:0.215338 
[16]    train-rmse:0.211162 
[1] train-rmse:0.410302 
[2] train-rmse:0.362318 
[3] train-rmse:0.328783 
[4] train-rmse:0.307210 
[5] train-rmse:0.293495 
[6] train-rmse:0.281758 
[7] train-rmse:0.272646 
[8] train-rmse:0.262005 
[9] train-rmse:0.253085 
[10]    train-rmse:0.246850 
[11]    train-rmse:0.239128 
[12]    train-rmse:0.232936 
[13]    train-rmse:0.226476 
[14]    train-rmse:0.220414 
[15]    train-rmse:0.213686 
[16]    train-rmse:0.209723 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">depth =</span> hyper_depth, <span class="at">eta =</span> hyper_eta, <span class="at">AUC =</span> tuning_results)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   depth         eta       AUC
1     49 0.988891729 0.7904927
2     65 0.946668233 0.7985711
3    153 0.082437558 0.8174663
4     74 0.514211784 0.8109768
5    146 0.390203467 0.8064756
6    122 0.905738131 0.7992766
7    200 0.446969628 0.8092398
8    128 0.836004260 0.8053466
9     47 0.737595618 0.8027806
10    24 0.811055141 0.8008673
11    71 0.388108283 0.8094556
12   100 0.685169729 0.8011198
13    89 0.003948339 0.8044831
14   165 0.832916080 0.8052938
15   110 0.007334147 0.8065934
16    20 0.207658973 0.8189459
17   154 0.906601408 0.8000982
18   114 0.611778643 0.8011920
19   111 0.379559241 0.8060280
20   131 0.435771585 0.8069872</code></pre>
</div>
</div>
<p>Make predictions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>data_xg <span class="ot">=</span> <span class="fu">xgb.DMatrix</span>(<span class="at">data =</span> <span class="fu">as.matrix</span>(data_obs[,<span class="sc">-</span><span class="dv">1</span>]), <span class="at">label =</span> data_obs<span class="sc">$</span>survived)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">xgboost</span>(data_xg, <span class="at">nrounds =</span> <span class="dv">16</span>L, <span class="at">eta =</span> results[<span class="fu">which.max</span>(results<span class="sc">$</span>AUC), <span class="dv">2</span>], <span class="at">max_depth =</span> results[<span class="fu">which.max</span>(results<span class="sc">$</span>AUC), <span class="dv">1</span>], <span class="at">objective =</span> <span class="st">"reg:logistic"</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> <span class="fu">as.matrix</span>(data_new)[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Single predictions from the ensemble model:</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="fu">data.frame</span>(<span class="at">y =</span> predictions), <span class="at">file =</span> <span class="st">"Max_titanic_xgboost.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>


</section>

</main> <!-- /main -->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/TheoreticalEcology\.github\.io\/machinelearning\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./A3-BiasVarianceTradeOff.html" class="pagination-link" aria-label="Managing algorithmic complexity">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Managing algorithmic complexity</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./B1-Trees.html" class="pagination-link" aria-label="Tree-based Algorithms">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tree-based Algorithms</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/TheoreticalEcology/machinelearning/edit/master/A4-MLpipeline.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>