install.packages("abind")
install.packages("animation")
install.packages("ape")
install.packages("BiocManager")
BiocManager::install(c("Rgraphviz", "graph", "RBGL"))
install.packages("coro")
install.packages("dbscan")
install.packages("dendextend")
install.packages("devtools")
install.packages("dplyr")
install.packages("e1071")
install.packages("factoextra")
install.packages("fields")
install.packages("forcats")
install.packages("glmnet")
install.packages("gym")
install.packages("kknn")
install.packages("knitr")
install.packages("iml")
install.packages("lavaan")
install.packages("lmtest")
install.packages("magick")
install.packages("mclust")
install.packages("microbenchmark")
install.packages("missRanger")
install.packages("mlr3")
install.packages("mlr3learners")
install.packages("mlr3measures")
install.packages("mlr3pipelines")
install.packages("mlr3tuning")
install.packages("paradox")
install.packages("partykit")
install.packages("pcalg")
install.packages("piecewiseSEM")
install.packages("purrr")
install.packages("randomForest")
install.packages("ranger")
install.packages("reticulate")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("scales")
install.packages("semPlot")
install.packages("stringr")
install.packages("tfprobability")
install.packages("tidyverse")
install.packages("torchvision")
install.packages("xgboost")

devtools::install_github("andrie/deepviz", dependencies = TRUE,
                         upgrade = "always")
devtools::install_github(repo = "florianhartig/EcoData", subdir = "EcoData",
                         dependencies = TRUE, build_vignettes = FALSE)
devtools::install_github('skinner927/reprtree')
devtools::install_version("lavaanPlot", version = "0.6.0")

reticulate::conda_install("r-reticulate", packages = "scipy", pip = TRUE)

torch::install_torch()


